server:
   port: 9820
mobile: 15289288565
project: qiusheng-web
spring:
   profiles:
      active: dev
   messages:
      basename: i18n/messages
      encoding: UTF-8
   jpa:
      database: mysql
      generate-ddl: true
      hibernate:
         ddl-auto: update
         naming:
            physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      show-sql: true

      properties:
         hibernate:
            session_factory:
               statement_inspector: com.happy.interceptor.AESInterceptor
management:
   security:
      enabled: false
security:
#   basic:
#      enabled: false
   oauth2:
      client:
         access-token-uri: http://localhost:9920/oauth/token
         user-authorization-uri: http://localhost:9920/oauth/authorize
         authorities: oauth2
         grant-type: password
         client-secret: 123456
         client-id: client_2
      resource:
         token-info-uri: http://localhost:9920/oauth/check_token
         user-info-uri: http://localhost:9920/uaa/user
         prefer-token-info: false #false使用user-info-uri，true使用token-info-uri
         filter-order: 3
         id: order
   user:
      name: user_1
      password: 123456
   #basic: false



idCenter:
   workerId: 2
   dataCenterId: 1
   zookeeper:
      host: 127.0.0.1:2181



#liquibase:
#   change-log: classpath:liquibase/master.xml
#   user: root
#   password: 123456
#   url: jdbc:mysql://localhost:3306/service
#   enabled: true
#   drop-first: false



