server:
   port: 9820
mobile: 15289288565
project: qiusheng-web
spring:
   profiles:
      active: dev
   messages:
      basename: i18n/messages
      encoding: UTF-8

idCenter:
   workerId: 2
   dataCenterId: 1
   zookeeper:
      host: 127.0.0.1:2181

#liquibase:
#   change-log: classpath:liquibase/master.xml
#   user: root
#   password: 123456
#   url: jdbc:mysql://localhost:3306/service
#   enabled: true
#   drop-first: false



